version: 2.1

orbs:

executors:
  ruby_containter:
    docker:
      - image: circleci/ruby:2.5
        environment:
          RAILS_ENV: test

commands:
  bundle_install:
    steps:
      - restore_cache:
          name: Restore Bundler Gemfile cache
          keys:
            - bundler-packages-v1-{{ checksum "Gemfile.lock" }}
      - run:
          name: Bundle Install
          command: |
            bundle install --jobs=4 --retry=3 --path=./vendor/bundle --frozen
      - save_cache:
          name: Save Bundler Package Cache
          key: bundler-packages-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - ./vendor/bundle
  rake_test:
    steps:
      - run:
          name: Ruby Tests
          command: |
            bundle exec rake test
      - store_test_results:
          # Should look like the directory passed to the JUnitReporter, minus
          # the final "minitest" directory
          path: "tmp/test_results"

jobs:
  build:
    parallelism: 1
    executor: ruby_containter
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - checkout
      - bundle_install
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    parallelism: 1
    executor: ruby_containter
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - bundle_install
      - rake_test

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
